In [1]:
#!pip install numpy

In [5]:
import numpy as np 

In [6]:
a=np.array([])
b=np.array([1,2,3,45,0])
c=np.array([[12,3,4],[4,5,8]])

In [8]:
a

array([], dtype=float64)

In [17]:
a.size

0

In [11]:
type(a)

numpy.ndarray

In [9]:
b

array([ 1,  2,  3, 45,  0])

In [12]:
type(b)

numpy.ndarray

In [18]:
b.size

5

In [10]:
c

array([[12,  3,  4],
       [ 4,  5,  8]])

In [20]:
c.shape

(2, 3)

In [13]:
type(c)

numpy.ndarray

In [14]:
c.ndim

2

In [19]:
c.size

6

In [15]:
b.ndim

1

In [16]:
a.ndim

1

In [21]:
n=np.array([ [2,3,4,5],[20,10,40,30],[200,100,600,700] ])

In [22]:
n.shape

(3, 4)

In [23]:
n.size

12

In [24]:
n.ndim

2

In [2]:
array([[1,2,3,4],
      [11,22,33,40],
      [5,7,9,90]])
      

NameError: name 'array' is not defined

In [7]:
m=np.array([[1,2,3,4],[11,22,33,40],[5,7,9,90]])

m

In [8]:
m

array([[ 1,  2,  3,  4],
       [11, 22, 33, 40],
       [ 5,  7,  9, 90]])

In [9]:
m[1,3]

40

In [10]:
m[0,3]

4

In [11]:
m[1,1],m[1,2]

(22, 33)