In [1]:
import numpy as np 

In [2]:
m=np.array([[1,2,3,4],[11,22,33,40],[5,7,9,90]])

In [3]:
m

array([[ 1,  2,  3,  4],
       [11, 22, 33, 40],
       [ 5,  7,  9, 90]])

In [5]:
m[0,1:3]

array([2, 3])

In [6]:
m[1:,2:]

array([[33, 40],
       [ 9, 90]])

In [8]:
m[1,:2]

array([11, 22])

m[0:3,3:]

In [10]:
m[0:3,3:]

array([[ 4],
       [40],
       [90]])

In [11]:
list(range(5,51))

[5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

In [12]:
np.arange(5,51)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [14]:
np.arange(5.5,50.5)

array([ 5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5, 14.5, 15.5,
       16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5, 23.5, 24.5, 25.5, 26.5,
       27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5,
       38.5, 39.5, 40.5, 41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5, 48.5,
       49.5])

# Reshape

In [24]:
a=np.arange(12).reshape(3,4)

In [20]:
np.sqrt(81)

9.0

In [25]:
a.max()

11

In [26]:
a.min()

0

In [27]:
a.argmax()

11

In [28]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
a.max()

11

In [30]:
a.min()

0

In [31]:
a.mean()

5.5

In [32]:
a.argmax()

11

In [33]:
a*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [35]:
a+10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

# Random

In [37]:
np.random.rand(2,2)

array([[0.8638003 , 0.57182177],
       [0.69836155, 0.2940706 ]])

In [38]:
np.random.rand(2)

array([0.84092444, 0.50687201])

In [39]:
np.random.randn(2,2)

array([[-0.5622894 , -2.05139116],
       [-1.19091384, -0.07341265]])

In [42]:
s=np.random.randint(9,90,12).reshape(6,2)

In [43]:
s.sum()

631

In [44]:
s.sum(axis=1)

array([ 88, 103,  93, 100, 153,  94])

In [45]:
s.sum(axis=0)

array([321, 310])

# 3D

In [48]:
[[[[4,40],[5,50],[6,60]],[[7,70],[8,80],[9,90],[[5,55],[4,40],[6,60]]]

SyntaxError: unexpected EOF while parsing (2923954232.py, line 1)